packages:
  - 'packages/**'

minimumReleaseAge: 1440

minimumReleaseAgeExclude:
  - astro
  - '@astrojs/markdown-remark'
  - '@astrojs/mdx'
  - '@astrojs/node'
  - '@astrojs/react'
  - '@astrojs/rss'
  - '@astrojs/sitemap'
  - '@xsynaptic/eslint-config'
  - '@xsynaptic/unified-tools'
  - 'rehype-wrap-cjk'
