packages:
  - packages/**

# Intended to mitigate supply chain attacks
minimumReleaseAge: 1440
verifyDepsBeforeRun: error
strictDepBuilds: true

minimumReleaseAgeExclude:
  - astro
  - '@astrojs/markdown-remark'
  - '@astrojs/mdx'
  - '@astrojs/node'
  - '@astrojs/react'
  - '@astrojs/rss'
  - '@astrojs/sitemap'
  - '@xsynaptic/eslint-config'
  - '@xsynaptic/unified-tools'
  - rehype-wrap-cjk

allowBuilds:
  esbuild: true
  sharp: true
